# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('theme', models.CharField(choices=[('theme', 'Original'), ('theme-aquatica', 'Aquatica'), ('theme-aspirin', 'Aspirin'), ('theme-blues', 'Blues'), ('theme-buddha', 'Buddha'), ('theme-campfire', 'Campfire'), ('theme-cobalt', 'Cobalt'), ('theme-dusk', 'Dusk'), ('theme-eco', 'Eco'), ('theme-matte', 'Matte'), ('theme-mustang', 'Mustang'), ('theme-rocklobster', 'Rocklobster'), ('theme-sunset', 'Sunset'), ('theme-tronic', 'Tronic'), ('theme-zest', 'Zest')], default='theme', max_length=30)),
                ('header', wagtail.wagtailcore.fields.StreamField((('bottom_text_header', wagtail.wagtailcore.blocks.StructBlock((('subheader', wagtail.wagtailcore.blocks.CharBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('centered_hero', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('subheader', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('centered_page_header', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('subheader', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('coming_soon_banner', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('note', wagtail.wagtailcore.blocks.CharBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('header_with_image', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('page_header', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('subheader', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock()))))), blank=True, null=True)),
                ('body', wagtail.wagtailcore.fields.StreamField((('centered_text', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('subheader', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock())))), ('fullwidth_map', wagtail.wagtailcore.blocks.StructBlock((('google_map_url', wagtail.wagtailcore.blocks.URLBlock()),))), ('inline_image_right', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('subheader', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('stat_counters', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('counters', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('number', wagtail.wagtailcore.blocks.CharBlock())), template='pivot/sections/_stat_counter.html')))))), ('text_columns', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('columns', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.RichTextBlock())), template='pivot/sections/_text_column.html')))))), ('text_features', wagtail.wagtailcore.blocks.StructBlock((('columns', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.RichTextBlock())), template='pivot/sections/_text_feature.html'))),))), ('text_on_image', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()))))), blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Social accounts',
            },
        ),
    ]
