# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivot', '0002_bottomtextheader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BottomTextHeader',
        ),
    ]
