# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 18:31
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pivot', '0006_auto_20160723_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pivotpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('centered_text', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('subheader', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock())))), ('fullwidth_map', wagtail.wagtailcore.blocks.StructBlock((('google_map_url', wagtail.wagtailcore.blocks.URLBlock()),))), ('google_form', wagtail.wagtailcore.blocks.StructBlock((('google_form_url', wagtail.wagtailcore.blocks.URLBlock()),))), ('inline_image_right', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('subheader', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('stat_counters', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('counters', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('number', wagtail.wagtailcore.blocks.CharBlock())), template='pivot/sections/_stat_counter.html')))))), ('text_columns', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('columns', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.RichTextBlock())), template='pivot/sections/_text_column.html')))))), ('text_features', wagtail.wagtailcore.blocks.StructBlock((('columns', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.RichTextBlock())), template='pivot/sections/_text_feature.html'))),))), ('text_on_image', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()))))), blank=True, null=True),
        ),
    ]
